version: "3"

services:

  nginx:
    container_name: symfony5_nginx
    image: nginx:1.19
    ports:
      - "81:80"
      - "444:443"
    volumes:
      - "./app/public/:/var/www/html/public"
      - "./env/nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
      - "./env/nginx/conf/vhosts.conf:/etc/nginx/conf.d/default.conf"
      - "./env/nginx/log:/var/log/nginx"
    links:
      - php
    depends_on:
      - php

  php:
    container_name: symfony5_php
    build:
      context: .
      dockerfile: ./env/php/Dockerfile
    environment:
      DATABASE_URL: "postgresql://symfony5:symfony5@postgres:5432/symfony5?serverVersion=13&charset=utf8"
    volumes:
      - "./app/:/var/www/html"
      - "./env/php/conf/php.ini:/usr/local/etc/php/php.ini"
    links:
      - postgres
    depends_on:
      - postgres

  postgres:
    container_name: symfony5_postgres
    image: postgres:13.1
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: symfony5
      POSTGRES_USER: symfony5
      POSTGRES_PASSWORD: symfony5
    volumes:
      - "./env/postgres/data:/var/lib/postgresql/data"