version: '3'

services:

  composer:
    container_name: symfony5_composer
    image: composer:latest
    command:
      - /bin/sh
      - -c
      - |
        composer install --no-interaction --ignore-platform-reqs --no-scripts
        chmod -R 777 /app/vendor
        mkdir /app/var
        chmod -R 777 /app/var
        echo 'Dependencies successfully installed'
    tty: true
    volumes:
      - "./app/:/app"